#!/usr/bin/env sh
set -eu

export ANDROID_HOME="${ANDROID_HOME:-/opt/homebrew/share/android-commandlinetools}"
export JAVA_HOME="${JAVA_HOME:-/opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home}"

cd "$(dirname "$0")/../apps/android"
exec gradle "$@"
